export default {
  ACTION_SELECT_CATEGORY: 'SELECT_CATEGORY',
  ACTION_LIST_CATEGORIES: 'LIST_CATEGORIES',
  ACTION_DELETE_CATEGORY: 'DELETE_CATEGORY',
  SAVE_CATEGORY_URL: '/api/categories',
  LIST_CATEGORIES_URL: '/api/categories/categories'
}
